<div id="footer" class="wrapper">

<div class="w450 floatl mt5">
<p>All rights reserved &copy; Bitar Arquitectos</p>
<p><a href="mailto:info@bitarqs.com" target="_blank">info@bitarqs.com</a></p>
</div>

<a href="https://www.facebook.com/pages/Bitar-Arquitectos/198317376958816" target="_blank" id="facebook">Like us in Facebook</a>

<div class="clearfix"></div><!-- /clearfix -->
</div><!-- / WRAPPER -->