	<link rel="shortcut icon" href="favicon.ico" />
		
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<meta name="author" content="Sandra Bermudez @ bulabe.com" />
	<meta name="description" content="Grupo fundado por Héctor Bitar, formado por arquitectos, ingenieros y diseñadores, dedicados a la arquitectura y diseño de interiores."/>
	<meta name="keywords" content="arquitectura, diseño, interiorismo, decoración, atmósferas, mobiliario, museografía, escenografía, construcción, despacho arquitectura mexicana, arquitectos, Bitar"/>
	
	<!--
	<meta name="HandheldFriendly" content="true" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	-->

	<meta property="og:title" content="Bitar Arquitectos" />
	<meta property="og:type" content="website" />
	<meta property="og:description" content="Grupo fundado por Héctor Bitar, formado por arquitectos, ingenieros y diseñadores, dedicados a la arquitectura y diseño de interiores." />
	<meta property="og:url" content="http://www.bitarqs.com" />
	<meta property="og:image" content="http://" />

	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600" />
	
	<link rel="stylesheet" type="text/css" href="style.css" />
	
	<script type="text/javascript" src="js/jquery-1.6.2.min.js"></script>
	<script type="text/javascript" src="js/jquery.frontend.js"></script>